[package]
name = "s"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", features = ["nightly", "vulkan", "gltf"] }
serde = { version = "*", features = ["derive"] }
specs-physics = "*"